<?php
 return array (
  'site_logo' => 'site_logo.png',
  'posp_application_fee' => '399',
  'rozar_secret' => 'LvlAjd1woF5HJEE5EAbXZj7n',
  'rozar_key' => 'rzp_live_TCKGzAhT4oF1F4',
  'pospID_prefix' => 'SF/POSP/A',
  'userID_prefix' => 'SF',
  'contact_address' => 'Office No. 31, Third Floor, Mahima\'s Triniti, Plot No-5, Swej Farm, New Sanganer Road, Sodala, Jaipur, Rajasthan-302019',
  'contact_phone' => '+91-141-4919086',
  'contact_fax' => '+91-141-4919086',
  'contact_email' => 'care@superfinserv.com',
  'facebook_url' => 'https://www.facebook.com/superfinserv/',
  'linkedin_url' => 'https://www.linkedin.com',
  'corporate_identity_no' => 'U74999RJ2017PTC058858',
  'irda_reg_no' => 'CA0643',
  'irda_valid_till' => '14 March 2025',
  'principal_officer' => 'Vipul Rawal',
  'copyright_content' => 'Copyright © 2021 superfinserv.in (All Rights Reserved)',
  'site_name' => 'SUPER FINSERV PRIVATE LIMITED',
  'site_url' => 'https://superfinserv.co.in',
  'cert_required_marks' => '50',
  'pan_no' => 'AAZCS1102K',
  'gstin_no' => '08AAZCS1102K1Z1',
  'app_under_maintenance' => 'NO',
  'app_version' => '0.0.2',
  'site_short_name' => 'Super Finserv',
  'uat_allowed_ip' => 'Super Finserv',
  'posp_site_url' => 'https://pos.superfinserv.co.in',
  'twitter_url' => 'https://twitter.com/SuperFinserv',
  'web_under_maintenance' => 'NO',
) ;